---
# tasks file for container
- name: pull {{ image }} 
  docker_image:
    name: "{{ image }}"
    source: pull

- name: Create container
  docker_container:
    name: "{{ nomcontainer }}"
    image: "{{ image }}"


