---
# tasks file for ec2

- name: créé ssh
  ec2_key:
    aws_access_key: "{{ access }}"
    aws_secret_key: "{{ key }}"
    region: eu-central-1
    name: delannoy_key_ansible
  register: ec2_key

- name: save private key
  copy: content="{{ec2_key.key.private_key}}" dest=/etc/ansible/delannoy_key_ansible.pem mode=0600
  when: ec2_key.changed


- name: création instances 
  ec2:
    aws_access_key: "{{ access }}"
    aws_secret_key:  "{{ key }}"
    key_name: "delannoy_key_ansible"
    instance_type: t2.micro
    group: default
    region: eu-central-1
    image: ami-0245697ee3e07e755
    count: 2
    count_tag:
      name: master
      name: worker
    instance_tags:
      Environment: Testing
  register: ec2

- name: debug
  debug:
    msg: "{{ ec2 }}"
    
- name: sauvegarde ip
  lineinfile:
    dest: "{{hosts_file}}"  
    insterafter: '\[webservers\]'
    line: "{{item.public.ip}}"
  with_items: "{{ec2.instances}}"
