---
# tasks file for mediawikDi

- name: update du cache
  apt:
    update_cache: yes  
- name: install apache

  apt: 

   name: apache2

   state: present


- name: install maria

  apt: 

   name: mariadb-server

   state: present



- name: install php7.4

  apt: 

   name: php7.4

   state: present



- name: install php-mysql

  apt: 

   name:  php-mysql

   state: present

- name: install libapache2-mod-php

  apt: 

   name: libapache2-mod-php

   state: present

- name: install php-xml

  apt: 

   name: php-xml

   state: present

- name: isntall php-mbstring
  apt:
    name: php-mbstring
    state: present


