---
# tasks file for mediawiki

- name: télécharger et décompresser mediawiki
  unarchive:
    src: https://releases.wikimedia.org/mediawiki/1.37/mediawiki-1.37.1.tar.gz
    dest: /var/lib/mediawiki
    remote_src: yes


